# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ripple.create!(name: 'QwertyMan', message: 'Have a holly jolly Christmas')
Ripple.create!(name: 'Dr.Claw', message: 'NEXT TIME GADGET')
Ripple.create!(name: 'Mr. Awesome', website: 'doctorawesome.com', message: 'I am awesome')
Ripple.create!(name: 'SillyMan', message: 'Have a holly jolly Easter')
Ripple.create!(name: 'Dr.Fantastic', message: 'NEXT TIME GIDGET')
Ripple.create!(name: 'Mrs. Awesome', website: 'mrsawesome.com', message: 'I am mrs. awesome. I help others to see their awesomeness. You can be awesome too. Woo hoo!')
Ripple.create!(name: 'FunnyMan', message: 'Have a holly jolly Valentines')
Ripple.create!(name: 'Dr.Dog', message: 'NEXT TIME PUPPY')
Ripple.create!(name: 'Mr. Amazing', website: 'doctoramazing.com', message: 'I am amazing. I work really hard to be amazing. I am the best in the world. You should call me awesome forever and ever. Take the time to say hi!')
Ripple.create!(name: 'Bob', message: 'Computer Science is awesome. We will create the machines that will destroy us lol')
Ripple.create!(name: 'Sally', message: 'Wow')
Ripple.create!(name: 'Mrs. M', website: 'mrsm.com', message: 'I love computers. They make everyday so much easier. Imagine your car without bluetooth navigation or your life without your phone. I am the last generation to grow up without the internet and I find it amazing. How lucky are we that we live in a world that is so connected by computers.')
Ripple.create!(name: 'QwertyMan', message: 'Have a holly jolly St Pattys')
Ripple.create!(name: 'Dr.Claw', message: 'NEXT TIME I WILL POPULATE THIS DATA DIFFERENTLY')
Ripple.create!(name: 'Mr. Awesome', website: 'doctorawesome.com', message: 'I am so great!')
Ripple.create!(name: 'SillyMan', message: 'Have a holly jolly THanksgiving')
Ripple.create!(name: 'Dr.Fantastic', message: 'NEXT TIME GIDGET')
Ripple.create!(name: 'Mrs. Awesome', website: 'mrsawesome.com', message: 'I am mrs. awesome. I help others to see their awesomeness. You can be awesome too')
Ripple.create!(name: 'FunnyMan', message: 'Have a holly jolly Valentines')
Ripple.create!(name: 'Dr.Dog', message: 'NEXT TIME PUPPY')
Ripple.create!(name: 'Mr. Bot',  message: 'I am a robot')
Ripple.create!(name: 'BobKicker', message: 'Computer Science is awesome. We will create the machines that will destroy us lol')
Ripple.create!(name: 'SallyJ', message: 'Wow what a great opportunity to learn all about ruby and rails!')
Ripple.create!(name: 'Mrs. Maga', website: 'mrsmaga.com', message: 'I love purses')
Ripple.create!(name: 'Sam', message: 'I am Sam, Sam I Am. I like green eggs and ham. I like them on a fox, I like them in a box. I like them on a train. I like them in the rain. Sam I am.')
Ripple.create!(name: 'Harry', website: 'potter.com', message: 'I fight for what is right')
Ripple.create!(name: 'Snape', message: 'Mr. Potter')
Ripple.create!(name: 'Hermoine', message: 'I love books. I love magic')
Ripple.create!(name: 'Ron',  message: 'I hate spiders.')
Ripple.create!(name: 'Dumbledore', message: 'Light always defeats dark')
Ripple.create!(name: 'Luna', message: 'I may be strange but at least I am happy')
Ripple.create!(name: 'Ginny', website: 'mrsmaga.com', message: 'I love Harry')


